language: python
python:
    - '3.8'

install:
    - pip install -r ./requirements.txt
    - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0

env:
    - PYTHONPATH=/home/travis/build/alisha-bhatia/hotspot

script:
    - make all_tests

#deploy to heroku on push to master
deploy:
    - provider: heroku
      api_key: $HEROKU_API_KEY
      app: teamhotspot
      on:
          branch: scratch/githubActions
